### ISSUE TITLE
Morph Transition from one activity to another

### ISSUE THREAD

**Issue by JitenNumberTank** [andremion/Music-Cover-View#2]
This is only working in one activity. I want transition from one activity to another activity. Could you tell me that how to make it from one activity to another activity.

**Comment by andremion** [comment]
Yes, you can use it in Activity Transitions with [MusicCoverViewTransition](https://github.com/andremion/Music-Cover-View/blob/master/library/src/main/java/com/andremion/music/MusicCoverViewTransition.java). Check out the project [Music-Player](https://github.com/andremion/Music-Player). I can add another snippet in README file later on.
