### ISSUE TITLE
Question about method 'morph()'

### ISSUE THREAD

**Issue by zyascend** [andremion/Music-Cover-View#3]
hello, I am wondering when the method 'morph()' in MusicCoverView.class at line 323 is called?

**Comment by zyascend** [comment]
Or is it nerver be called? Thanks

**Comment by andremion** [comment]
Hi @zyascend,

The [morph](https://github.com/andremion/Music-Cover-View/blob/master/library/src/main/java/com/andremion/music/MusicCoverView.java#L353) method is called externally.
It's used to start a transition from/to the rect/circle shape.

Check the [sample](https://github.com/andremion/Music-Cover-View/blob/master/sample/src/main/java/com/andremion/music/sample/MainActivity.java) usage.

**Comment by zyascend** [comment]
I am so sorry. I didn't check the sample of this project. I just watched you anther project Music-Player which I  couldn't find where 'morph()' was called. Now I got it. Anyway, thanks for your reply. Looking forward to your next awesome work ^_^.

**Comment by andremion** [comment]
No problem.
Soon I gonna publish another little project. Stay tuned!
😉
