### ISSUE TITLE
MinSDK Version AndroidManifest.xml

### ISSUE THREAD

**Issue by AbreuY** [andremion/Music-Cover-View#5]
Is it necessary for the minimum version of the SDK to be 21?
Can it be placed at 15? Does it cause any incompatibility?

**Comment by andremion** [comment]
For now, yes.
`clipPath` doesn't work well.

<img src=https://user-images.githubusercontent.com/12762356/58042216-fbd27b00-7b31-11e9-8d4f-64a18372487b.gif alt=music-cover-view width=200>
